version: '3'

volumes:
  database:
    driver: local

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: veles
    ports:
      - "27022:27017"
    volumes:
      - database:/data/db

  app:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3002:3002"
    command: ./start.sh
